pipeline:
  # Fetch folders from distributed cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  tests:
    image: scalaplatform/scala:0.6
    pull: true
    volumes:
      - /platform:/keys
    commands:
      - git log | head -n 20
      - sbt $TEST

  notify:
    image: drillster/drone-email
    host: smtp.mailgun.org
    username: noreply@drone.geirsson.com
    password: ${MAILGUN_PASSWORD}
    from: noreply@drone.geirsson.com
    recipients:
      - olafurpg@gmail.com
    when:
      event: push
      branch: [master]
      status: [changed, failure]

  # Save folders in distributed cache
  sftp_cache_rebuild:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
matrix:
  include:
    - TEST: ci-fast
      SCALA_VERSION: 2.11.8
    - TEST: ci-fast
      SCALA_VERSION: 2.12.1
    - TEST: ci-slow
