pipeline:
  tests:
    image: scalaplatform/scala:1.2
    environment:
      - BINTRAY_USERNAME=foo_user
      - BINTRAY_PASSWORD=foo_password
    pull: true
    commands:
      - git fetch --tags && git log | head -n 20
      - ./scalafmt --test
      - /usr/bin/sbt $CI_TEST

  publish:
    image: olafurpg/scalafix:0.3.0
    pull: true
    volumes:
      - /platform:/keys
    commands:
      - ./bin/publish.sh
    when:
      event: [push, tag]
      branch: [master]

matrix:
  include:
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.11.11
      CI_PUBLISH: true
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.12.2
    - CI_TEST: ci-slow
      CI_SCALA_VERSION: 2.11.11
