build:
  image: danieletorelli/sbt
  environment:
    - COURSIER_CACHE=/drone/cache/coursier
  commands:
    - export SBT_OPTS="-Xmx24G -XX:MaxPermSize=4G -Xss4M"
    - sbt ++$SCALA_VERSION clean test scripted
matrix:
  SCALA_VERSION:
    - 2.11.8
    - 2.12.1
cache:
  mount:
    - /drone/cache
