language: scala
script:
- "./bin/runci.sh $CI_TEST"
jdk:
- oraclejdk8
env:
  matrix:
  - CI_TEST: ci-fast-211

  - CI_TEST: ci-fast-212
    CI_PUBLISH: true

  - CI_TEST: ci-slow

  - CI_TEST: scalafmt

  - CI_TEST: mima

cache:
  directories:
  - "$HOME/.coursier"

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
- rm -rf $HOME/.ivy2/local

after_success:
- "./bin/ci-publish.sh"
