language: scala
script:
- "./bin/runci.sh $CI_TEST"
jdk:
- oraclejdk8
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - env: TEST="scalafmt"
      script: ./scalafmt --test
    - env: TEST="2.11"
      script: sbt ci-211
    - env: TEST="2.12"
      script: sbt ci-212
    # Disabled until stable v0.6
    # - env: TEST="mima"
    #   script: sbt mima
    - stage: release
      script: sbt ci-release
    # coverage
    - env: TEST="Coverage" CI_COVERAGE="true"
      script: sbt ";clean;coverage;ci-212;coverageReport"


cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"

after_success:
  - bash "[[ -v CI_COVERAGE ]] && bash <(curl -s https://codecov.io/bash)"

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
- rm -rf $HOME/.ivy2/local
