language: scala
script:
- "./bin/runci.sh $CI_TEST"
jdk:
- oraclejdk8
env:
  matrix:
  - CI_TEST: ci-fast
    CI_SCALA_VERSION: 2.11.11
    CI_SBT_VERSION: 0.13.16

  - CI_TEST: ci-fast
    CI_SCALA_VERSION: 2.12.3
    CI_SBT_VERSION: 0.13.16
    CI_PUBLISH: true

  - CI_TEST: ci-slow
    CI_SCALA_VERSION: 2.12.3
    CI_SBT_VERSION: 0.13.16

  - CI_TEST: ci-slow
    CI_SCALA_VERSION: 2.12.3
    CI_SBT_VERSION: 1.0.3

  - CI_TEST: mima
    CI_SBT_VERSION: 0.13.16

  - CI_TEST: scalafmt

cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
- rm -rf $HOME/.ivy2/local

after_success:
- "./bin/ci-publish.sh"
