name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  windows_213:
    name: Windows/scala_2.13 tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: sbt ci-213-windows
        shell: bash
