name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu"]
        jvm: ["11", "17", "21", "22"]
        include:
          - os: windows
            jvm: 21
    name: ${{ matrix.os }} / JDK${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          jvm: zulu:${{ matrix.jvm }}
      - if: ${{ matrix.os != 'windows' }}
        run: sbt test
      - if: ${{ matrix.os == 'windows' }}
        run: sbt testWindows
  docs:
    name: Compile docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
      - run: sbt ci-docs
  formatting:
    name: Scalafmt and Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
      - run: ./bin/scalafmt --test
      - run: sbt "dogfoodScalafixInterfaces; scalafixAll --check"
  mima:
    name: Version Policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
      - run: sbt versionPolicyCheck
