name: Deploy Website
on:
  push:
    branches: [main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
      - uses: sbt/setup-sbt@v1
      - name: Publish ${{ github.ref }} (without wiping sonatype-stats)
        run: |
          git restore --source=origin/gh-pages --worktree sonatype-stats
          mv ./sonatype-stats ./website/static
          sbt docs2_13/docusaurusPublishGhpages
        env:
          GITHUB_DEPLOY_KEY: ${{ secrets.DOC }}
